### ISSUE TITLE
Consult the direction of the project

### ISSUE THREAD

**Issue by lb091188** [xland/QuickUI#2]
粗略看了下您仓库中的代码，发现你貌似是想基于 quickjs 和 webui 两个库构建一个简单通用的 desktop 解决方案对吗？
作为一个web前端开发对此比较感兴趣，想了解下大概何时能够完成所有的代码编写。

After a quick look at the code in your repository, it looks like you're trying to build a simple generic desktop solution based on two libraries, quickjs and webui, right?
As a web frontend developer, I'm interested in seeing when all the code will be ready.

_ps: 本来想知乎咨询的，但最终还是忍不住开了这个 issus 怕您在知乎上看不到这个消息_

**Comment by xland** [comment]
> 基于 quickjs 和 webui 两个库构建一个简单通用的 desktop 解决方案

是，但估计只能尽量通用。

> 大概何时能够完成所有的代码编写

很难估计结束时间。

**Comment by lb091188** [comment]
虽然不懂 cpp ，但是能够猜到工作量有多大😁,会持续关注的。感谢大佬

**Comment by lb091188** [comment]
[Sciter with Quickjs](https://docs.sciter.com/docs/intro/) 大佬，最近发现了这个东西，有点接近你的设想，粗略看了下，语法已经比较接近 W3C 的规范了。如果合适的话，我感觉你可以基于这个再去做拓展而非 WebUI（个人感觉资源占用其实不低，毕竟是新开了一个浏览器） 。

**Comment by xland** [comment]
谢谢你的建议。

这个项目和WebUI的实现原理并不相同。
比如，它对CSS的支持是有一部分缺失的。
开发者无法 `真正` 的像开发Web页面一样使用它开发桌面应用界面。
